services:
  fastapi-service:
    build: .
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
      interval: 30s
      timeout: 10s
      retries: 3